[package]
name = "vsswrap"
version = "0.1.0"
authors = ["Kevin Darlington <kevin@outroot.com>"]

[dependencies]
time = "0.1"
winapi = "0.2"
kernel32-sys = "0.2"
kernel32x = { path = "lib/kernel32x" }
simplelog = "0.4"
log = "0.3"
clap = "2.24"